---
title: "M&M Frequency Distribution"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# SETUP CHUNK ------------------------------------------------------------------
# Load required packages. Install if needed.
library(flexdashboard)
library(gsheet)
library(dplyr)
library(leaflet)
library(plotly)
library(data.table)

# Fetch data from google docs
URL <- 'https://docs.google.com/spreadsheets/d/1rQZasD4o2aLTf3-sfcFt0TMiRJudWOR_qW7ZXgw8Jt8/edit?usp=sharing'
mnm_data <- gsheet2tbl(URL)

```

Column
-----------------------------------------------------------------------

### Total 

```{r}

# FREQUENCY DISTRIBUTION OF M&MS ---------------------------------------------------------------

# Count occurrences
mnm_count <- table(mnm_data[,"Total"])
mnm_count <- data.frame(mnm_count)
names(mnm_count) <- c("Total", "Frequency")

# Plot counts
plot_ly(data = mnm_count, x = ~Total, y = ~Frequency) %>%
    layout(xaxis = list(title = ''),
           yaxis = list(title = 'Frequency'))

```
